### ISSUE TITLE
jQuery app week 2 checklist.

### ISSUE THREAD

**Issue by yoni-mor** [yoni-mor/Web-App-jQuery#2]
- [x] Handlebars: dynamic dropdown background icons (inline-styles).
- [x] Handlebars: refactor tabs in a single template.
- [x] Handlebars: increment report indexes by 1 (to start with 1 instead of 0).

Quoted from @alexilyaev:
- [x] Note that you have ` id="nav1" ` set for all of them. You can use the `@index` to make it dynamic.
Also ` aria-describedby="menu-hint-1"
